name: Power Pages CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (e.g. dev, test, prod)'
        required: true
        default: 'main'

jobs:
  deploy:
    name: Deploy Power Pages
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Install Power Platform CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool

      - name: Set Environment URL
        run: |
          echo "ENV_URL=${{ secrets[format('ENVIRONMENT_URL_{0}', github.event.inputs.environment) || 'ENVIRONMENT_URL'] }}" >> $GITHUB_ENV

      - name: Authenticate with Power Platform
        run: |
          pac auth create --applicationId ${{ secrets.CLIENT_ID }} `
                          --clientSecret ${{ secrets.CLIENT_SECRET }} `
                          --tenant ${{ secrets.TENANT_ID }} `
                          --environment ${{ secrets.ENV_URL }}

      - name: Upload Portal Changes
        run: |
          pac paportal upload --path src/MyPortal/test---site-e6pz4 --modelVersion 2
